In [3]:
import numpy as np
np.full((3, 2), 7)

a=np.arange(10).reshape((2, 5))
print(a)
print(np.mean(a), np.mean(a, axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]]
4.5 [2.5 3.5 4.5 5.5 6.5]


In [2]:
a = np.random.random((10, 3))
print(a)
b = np.argmin(abs(a-0.5), axis=1)
print(b)

for i in range(10):
    print(a[i,b[i]])

[[0.91013896 0.53822226 0.97901739]
 [0.63971326 0.72611906 0.79366821]
 [0.53481719 0.96827172 0.17946075]
 [0.7834535  0.12050042 0.19455183]
 [0.222857   0.66138227 0.84226076]
 [0.30344483 0.57107134 0.10327736]
 [0.62963736 0.28826881 0.51300369]
 [0.5838966  0.62549451 0.97929632]
 [0.92470214 0.84116911 0.27653811]
 [0.01924503 0.40034652 0.86503827]]
[1 0 0 0 1 1 2 0 2 1]
0.5382222598074368
0.6397132619200252
0.5348171931085393
0.7834535009630603
0.6613822737013262
0.571071337037924
0.513003687803507
0.5838966000770126
0.27653811412337914
0.4003465178941311


In [3]:
a = np.random.random((6,6))
print(a)
b = np.argmin(a, axis = 0)
print(b)
for i in range(6) :
    print(sum(a[i])/a[b[i],i])

[[0.26167277 0.58566677 0.27873082 0.48441157 0.18055855 0.91500029]
 [0.79561537 0.69654684 0.35353998 0.64798684 0.0510293  0.43063801]
 [0.05819202 0.97838939 0.85342688 0.65878835 0.48246877 0.36526506]
 [0.0783277  0.41301205 0.70408913 0.36004483 0.57498954 0.79692384]
 [0.45480578 0.1111994  0.79657727 0.25896266 0.52548352 0.31064219]
 [0.0484185  0.30488333 0.09194153 0.05753562 0.25536386 0.14481476]]
[5 4 5 5 1 5]
55.8885656455926
26.75694506885185
36.942289510893055
50.87956284115541
48.16195232155154
6.235259404507703


In [4]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
i=0
b = []
while i<len(x)-1:
    if x[i+1]==0 :
        b.append(x[i])
    i+=1
      
print(b)      
print(np.max(b))        

[2, 3, 0, 7]
7


In [5]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for k in range(len(i)):
    x[i[k]]+=1
    
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
